name: model-training
on:
  push:
    paths:
    - '**.py'
    - 'requirements.txt'
    - '.github/**'
jobs:
  run:
    runs-on: [ubuntu-latest]
    container: docker://dvcorg/cml-py3:latest
    steps:
      - uses: actions/checkout@v2
      # - uses: actions/setup-python@v2
      # - uses: iterative/setup-cml@v1
      - name: Train model
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "START PYTHON VERSION"
          echo "python version:" $(python --version)
          echo "python3 version:" $(python3 --version)
          echo "Which python:" $(which python)
          echo "Which python3:" $(which python3)
          echo "pip version:" $(pip --version)
          echo "END PYTHON VERSION"
          apt-get install python3-venv
          python3 -m venv .venv
          source .venv/bin/activate
          pip install --upgrade pip 
          pip install -r requirements.txt
          echo "TRAINING STARTING"
          python train.py
          echo "TRAINING COMPLETE"

          cat metrics.txt >> report.md
          cml publish plot.png --md >> report.md
          cml send-comment --pr --publish --commit-sha=HEAD --token $REPO_TOKEN report.md 

          echo "MODEL METRICS"
          cat metrics.txt
